language: c

os: linux

matrix:
  include:
  - name: "GCC Debug"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
    before_script:
      - cd ext/avif/ext
      - bash aom.cmd
      - cd ../../..
      - mkdir build
      - cd build
      - cmake -G Ninja -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DCMAKE_BUILD_TYPE=Debug ..
    script:
      - ninja

  - name: "GCC Release"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
    before_script:
      - cd ext/avif/ext
      - bash aom.cmd
      - cd ../../..
      - mkdir build
      - cd build
      - cmake -G Ninja -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DCMAKE_BUILD_TYPE=Release ..
    script:
      - ninja

  - name: "Clang Debug"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
    before_script:
      - cd ext/avif/ext
      - bash aom.cmd
      - cd ../../..
      - mkdir build
      - cd build
      - cmake -G Ninja -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DCMAKE_BUILD_TYPE=Debug ..
    script:
      - ninja

  - name: "Clang Release"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
    before_script:
      - cd ext/avif/ext
      - bash aom.cmd
      - cd ../../..
      - mkdir build
      - cd build
      - cmake -G Ninja -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DCMAKE_BUILD_TYPE=Release ..
    script:
      - ninja

  - name: "Clang Test IO"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
    before_script:
      - cd ext/avif/ext
      - bash aom.cmd
      - cd ../../..
      - mkdir build
      - cd build
      - cmake -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DCMAKE_BUILD_TYPE=Release -DCOLORIST_TEST_IO=1 ..
    script:
      - make -j colorist-test-io
